---

- hosts: redhat
  tasks:
    - name: Upgrade RHEL/CentOS hosts
      yum: name=* update_cache=yes state=latest exclude=nginx*

- hosts: freebsd
  tasks:
    - name: Upgrade FreeBSD hosts
      pkgng: name=* state=latest

- import_playbook: restart-services-playbook.yml
